### ISSUE TITLE
Cannot display the version of the binary

### ISSUE THREAD

**Issue by gdavison** [bflad/tfproviderlint#39] opened 2020-01-08 22:07 UTC
The usual suspects, `version` or `-version`, don't work:

```
$ tfproviderlint version
-: cannot find package "version" in any of:
	/usr/local/Cellar/go/1.13.5/libexec/src/version (from $GOROOT)
	/Users/gdavison/developer/go/src/version (from $GOPATH)
tfproviderlint: error during loading
```
```
$ tfproviderlint -version
flag provided but not defined: -version
...
  -V	print version and exit
...
```

Aha! Alas:

```
$ tfproviderlint -V
tfproviderlint: unsupported flag value: -V=true
```

**Comment by bflad** [comment] 2020-01-09 03:30
Duplicate of #22 😉

**Closed by bflad** 2020-01-09 03:30 UTC
